blog/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views


app_name = 'view_blog'

urlpatterns = [
    path('', views.home,  name = 'home'),
    path('posts/', views.view_all_publi_posts,  name = 'all_publi_posts'),
    path('login/', views.login_view,  name = 'login'),
    path('logout/', views.logout_view,  name = 'logout'),
    path('tech/<int:tech_pk>', views.view_all_publi_posts, name = 'view_all_publi_posts_tech'),
    
    path('manage/', views.view_all_unpubli_posts,  name = 'all_unpubli_posts'),
    path('new_post/', views.create_post,  name = 'create_post'),
    path('edit_post/<int:pk>', views.edit_post,  name = 'edit_post'),
    path('delete/<int:pk>', views.delete_post, name = 'delete_post'),
    path('view/<int:pk>', views.view_post, name = 'view_post'),
    path('published/<int:pk>/<str:publi>', views.change_post_status, name = 'change_post_status'),
]

blox_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', views.home),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class News(models.Model):
    title = models.CharField(max_length = 100)
    body_content = models.TextField()
    description = models.TextField(default = "Open the post to read more about!", max_length = 600)
    category_id = models.ForeignKey('Category',on_delete=models.CASCADE)
    publi = models.BooleanField(default = False)
    date_create = models.DateField(auto_now_add = True)
    author = models.CharField(max_length = 100)

    
class Category(models.Model):
    tech = models.CharField(max_length = 50)
    usecase = models.CharField(max_length = 100)
    description = models.TextField(default = "")

blog/views.py
from django.shortcuts import render, redirect
from .models import Category, News
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django.core.mail import send_mail
from django.contrib.auth.models import User

def logout_view(request):
    logout(request)
    return render(request, 'blog/index.html', context = {'modal_msg' : "Logout realizado com sucesso!"})


def notify_staff(msg):
    
    users = User.objects.all().filter(is_staff = 1)
    
    for user in users:
        subject = "Simulação envio de email" 
        body = {
        'first_name': user.first_name, 
        'last_name': user.last_name, 
        'email': user.email, 
        'message':msg, 
        }
        message = "\n".join(body.values())
        try:
            send_mail(subject, message, "admin@example.com", ['admin@example.com']) 
        except:
            pass
    
def home(request):
    return render(request, 'blog/index.html')
    # Redirect to a success page.
    
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, 'blog/index.html', context = {'modal_msg' : "Login realizado com sucesso!"})
        else:
            return render(request, 'blog/index.html', context = {'modal_msg' : "Erro ao logar"})
    return render(request, 'blog/login.html')
    
    
    
# @cache_page(60 * 10)
@login_required(login_url='/blog/login/')
def view_all_unpubli_posts(request):
    print("view_all_unpubli_posts")
    posts = News.objects.all()
    return render(request, 'blog/manage.html', context = {'posts' : posts})

# @cache_page(60 * 10)
def view_all_publi_posts(request, tech_pk = 0):
    tech_options = Category.objects.all()
    print("view_all_publi_posts")
    if tech_pk == 0:
        posts = News.objects.all().filter(publi = True)
    else:
        posts = News.objects.all().filter(publi = True, category_id = tech_pk)
    return render(request, 'blog/all_posts.html', context = {'posts' : posts, 'tech_options':tech_options})


def view_post(request, pk):
    try:
        post = News.objects.get(pk = pk)
        if post.publi or request.user.is_authenticated:
            return render(request, 'blog/view_post.html', context = {'post' : post})
        else:
            return render(request, 'blog/index.html', context = {'modal_msg' : "Sem permissão para visualizar essa postagem!"})
    except:
        return render(request, 'blog/index.html', context = {'modal_msg' : "Post inexistente!"})


@login_required(login_url='/blog/login/')
def delete_post(request, pk):
    try:
        News.objects.get(pk = pk).delete()
    except:
        pass
    return redirect("view_blog:all_unpubli_posts")


@login_required(login_url='/blog/login/')
def change_post_status(request, pk, publi):
    try:
        post = News.objects.get(pk = pk)
        post.publi = publi
        post.save()
    except:
        pass
    return redirect("view_blog:all_unpubli_posts")


@login_required(login_url='/blog/login/')
def create_post(request):
    
    tech_options = Category.objects.all()
    
    if request.method == 'POST':
            dict_form = {}
            for key, value in request.POST.items():
                if value != "":
                    dict_form[key] = value
                else:
                    return render(request, 'blog/create_post.html',{'modal_msg':"Todos os campos precisam ser preenchidos!",'tech_options':tech_options})
            try:          
                post = News()
                post.title = dict_form['Title']
                post.author = dict_form['Author']
                post.category_id = Category.objects.get(pk = dict_form['Tech'])   
                post.description = dict_form['Description']
                post.body_content = dict_form['BodyContent']
                post.save()    
                notify_staff("O seguinte post foi criado:\
                    Titulo: {post.title} \
                    Autor: {post.author} \
                    Descriação:{post.description} \
                    ")
                return render(request, 'blog/create_post.html',{'modal_msg':"Post criado com sucesso!",'tech_options':tech_options})
            except Exception as e:
                return render(request, 'blog/create_post.html',{'modal_msg':e,'tech_options':tech_options})
    else:
        return render(request, 'blog/create_post.html',{'tech_options':tech_options})
    
    
@login_required(login_url='/blog/login/')
def edit_post(request, pk):
    tech_options = Category.objects.all()
    post = News.objects.get(pk = pk)

    if request.method == 'POST':
            dict_form = {}
            for key, value in request.POST.items():
                if value != "":
                    dict_form[key] = value
                else:
                    return render(request, 'blog/edit_post.html',{'modal_msg':"Todos os campos precisam ser preenchidos!"})
            try:    
                      
                post = News.objects.get(pk = pk)
                post.title = dict_form['Title']
                post.author = dict_form['Author']
                post.category_id = Category.objects.get(pk = dict_form['Tech'])   
                post.description = dict_form['Description']
                post.body_content = dict_form['BodyContent']
                post.save()   
                notify_staff("O seguinte post foi editado:\
                            Titulo: {post.title} \
                            Autor: {post.author} \
                            Descriação:{post.description} \
                             ")
                return render(request, 'blog/edit_post.html',{'modal_msg':"Edição realizada com sucesso!",'tech_options':tech_options, 'post' : post})
            except Exception as e:
                return render(request, 'blog/edit_post.html',{'modal_msg':e,'tech_options':tech_options, 'post' : post})
    else:
        return render(request, 'blog/edit_post.html',{'tech_options':tech_options, 'post' : post})
    

blox_project/views.py
from django.shortcuts import render, redirect

def home(request):
    return redirect("view_blog:all_publi_posts")

blog/templates/blog/all_posts.html
{% extends 'blog/base.html' %}

{% block content %}
<br>



<div class = "row">
<div class = "container col-lg-8 col-md-8 col-sm-10">
<br>
<br>
    {% for post in posts %}
        <div class="list-group  my-4">
            <a href='{% url "view_blog:view_post" post.id %}' class="list-group-item list-group-item-action flex-column">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text"><small class="text-muted">{{ post.category_id.tech }} -> {{ post.category_id.usecase }}</small></p>
                    <p class="card-text">{{ post.description }}</p>
                    <p class="card-text"><small class="text-muted">{{ post.author }} - {{ post.date_create|date:"d/m/Y" }}</small></p>
                </div>
            </a>    
        </div>
    {% endfor %}

    </div>
    <div class="container  col-lg-1 col-md-3 col-sm-12 list-group">
        <a href='{% url "view_blog:all_publi_posts" %}' class="list-group-item list-group-item-action">Todos</a>
        {% for tech in tech_options %}
        <a href='{% url "view_blog:view_all_publi_posts_tech" tech.id %}' class="list-group-item list-group-item-action">{{tech.tech}}</a>
        {% endfor %}
    </div>
</div>



{% endblock %}


{% block script %}


{% endblock %}

blog/templates/blog/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand mx-3" href="{% url 'view_blog:home' %}">Blox</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">

              <li class="nav-item">
                <a class="nav-link" href="{% url 'view_blog:all_publi_posts' %}">Pagina Inicial</a>
              </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'view_blog:all_unpubli_posts' %}">Gerenciador</a>
            </li>
            {% endif %}
            {% if not user.is_authenticated %}
            <li class="nav-item right">
              <a class="nav-link" href="{% url 'view_blog:login' %}">Login</a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item right">
              <a class="nav-link" href="{% url 'view_blog:logout' %}">Logout</a>
            </li>
            {% endif %}
        </div>

      </nav>


    {% block content %}
    {% endblock %}
    
    
   <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js"></script>
    


    {% block script %} 
    {% endblock %}
  </body>
</body>

</html>

blog/templates/blog/create_post.html
{% extends 'blog/base.html' %}

{% block content %}
<br>

<div class = "container col-lg-10 col-md-8 col-sm-10">

     
<form method="post">
    {% csrf_token %}

    <div class="row">
        <div class="form-group col-md-8">
            <label for="inputTitle">Titulo</label>
            <input type="text" class="form-control" id="inputTitle" name = "Title" placeholder="Titulo" />
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-4">
            <label for="inputAuthor">Autor</label>
            <input type="text" class="form-control" id="inputAuthor" name = "Author" placeholder="Autor" />
        </div>
        <div class="form-group col-md-4">
            <label for="inputTech">Tecnologia</label>
            <select id="inputTech" name = "Tech" class="form-control" />
            {% for tech in tech_options %}
                <option value = {{ tech.id }}>{{ tech.tech }}</option>
            {% endfor %}
            </select>
          </div>
    </div>
    <div class="form-group col-md-8">
        <label for="inputDescription">Descrição</label>
        <textarea class="form-control" id="inputDescription" name = "Description" rows="3"></textarea>
    </div>
    <div class="form-group col-md-8">
        <label for="inputBodyContent">Conteudo</label>
        <textarea class="form-control" id="inputBodyContent" name = "BodyContent" rows="10"></textarea>
    </div>

    <br>
    <a  href="{% url 'view_blog:all_unpubli_posts' %}" class="btn btn-light col-md-1">Voltar</a>
    <button type="submit" class="btn btn-primary col-md-1">Salvar</button>
    </form>
</div>


{% endblock %}


{% block script %}
<script>
    window.onload = function () {  
        const msg_modal = '{{ modal_msg }}';
        if (msg_modal != ""){
            bootbox.alert(msg_modal);
        }
    };
</script>

{% endblock %}

blog/templates/blog/edit_post.html
{% extends 'blog/base.html' %}

{% block content %}
<br>

<div class = "container col-lg-10 col-md-8 col-sm-10">

     
<form method="post">
    {% csrf_token %}

    <div class="row">
        <div class="form-group col-md-8">
            <label for="inputTitle">Titulo</label>
            <input type="text" class="form-control" id="inputTitle" name = "Title" placeholder="Titulo" />
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-4">
            <label for="inputAuthor">Autor</label>
            <input type="text" class="form-control" id="inputAuthor" name = "Author" placeholder="Autor" />
        </div>
        <div class="form-group col-md-4">
            <label for="inputTech">Tecnologia</label>
            <select id="inputTech" name = "Tech" class="form-control" />
            {% for tech in tech_options %}
                <option value = {{ tech.id }}>{{ tech.tech }}</option>
            {% endfor %}
            </select>
          </div>
    </div>
    <div class="form-group col-md-8">
        <label for="inputDescription">Descrição</label>
        <textarea class="form-control" id="inputDescription" name = "Description" rows="3"></textarea>
    </div>
    <div class="form-group col-md-8">
        <label for="inputBodyContent">Conteudo</label>
        <textarea class="form-control" id="inputBodyContent" name = "BodyContent" rows="10"></textarea>
    </div>

    <br>
    <a  href="{% url 'view_blog:all_unpubli_posts' %}" class="btn btn-light col-md-1">Voltar</a>
    <button type="submit" class="btn btn-primary col-md-1">Salvar</button>
    </form>
</div>


{% endblock %}


{% block script %}

<script>
    window.onload = function () {    
        document.getElementById("inputTitle").value = "{{ post.title }}"
        document.getElementById("inputAuthor").value = "{{ post.author }}"
        document.getElementById("inputTech").value = "{{ post.category_id.id }}"
        document.getElementById("inputDescription").value = "{{ post.description }}"
        document.getElementById("inputBodyContent").value = "{{ post.body_content }}"
    
        const msg_modal = '{{ modal_msg }}';
        if (msg_modal != ""){
          bootbox.alert(msg_modal);
        }
    }
</script>

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
<br>

<div class = "container col-lg-10 col-md-8 col-sm-10">
<br>
<br>


    <h5>Bem vindo ao Blog Blox</h5>

</div>

</div>


{% endblock %}


{% block script %}

<script>
    window.onload = function () {  
        const msg_modal = '{{ modal_msg }}';
        if (msg_modal != ""){
            bootbox.alert(msg_modal);
        }
    };
</script>
{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% block content %}
<br>

<div class = "container">
    <br>
    <br>
    <div class = "row">

<form method="post">
    {% csrf_token %}

    <div class="row">
        <div class="form-group col-md-2"></div>
        <div class="form-group col-md-4">
            <label for="inputLogin">Login</label>
            <input type="text" class="form-control" id="inputLogin" name = "username" placeholder="Login" />
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-2"></div>
        <div class="form-group col-md-4">
            <label for="inputPassword">Senha</label>
            <input type="text" class="form-control" id="inputPassword" name = "password" placeholder="Senha" />
        </div>
    </div>
    <div class="row">
    <div class="form-group col-md-2"></div>
    <button type="submit" class=" my-3 btn btn-success col-md-1">Login</button>
    </div>
    </div>

</form>
</div>

</div>


{% endblock %}


{% block script %}


{% endblock %}

blog/templates/blog/manage.html
{% extends 'blog/base.html' %}

{% block content %}
<br>

<div class = "container col-lg-10 col-md-8 col-sm-10">
<br>

    <div class="list-group  my-4 ">
        <div class="d-flex w-100 justify-content-between align-items-center ">
            <a href='{% url "view_blog:create_post" %}' class="list-group-item list-group-item-action" >    
            
            <div class="my-1 col-8">
                <h1 class="text-muted"><i class="material-icons text-secondary" style="font-size:32px;" >add_box</i> Novo Post</h1>
            </div>
        </a>
        </div>   
    </div>

<br>
  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <a class="nav-item nav-link active" id="nav-allPosts-tab" data-toggle="tab" href="#nav-allPosts" role="tab" aria-controls="nav-allPosts" aria-selected="true">Todos</a>
      <a class="nav-item nav-link" id="nav-allPubli-tab" data-toggle="tab" href="#nav-allPubli" role="tab" aria-controls="nav-allPubli" aria-selected="false">Publicados</a>
      <a class="nav-item nav-link" id="nav-allUnpubli-tab" data-toggle="tab" href="#nav-allUnpubli" role="tab" aria-controls="nav-allUnpubli" aria-selected="false">Não Publicados</a>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-allPosts" role="tabpanel" aria-labelledby="nav-allPosts-tab"> 
        {% for post in posts %}
        <div class="list-group  my-4 ">
            {% if post.publi %}
                <a  class="list-group-item list-group-item-action flex-column border-success" >
            {% else %}
                <a  class="list-group-item list-group-item-action flex-column border-warning" >
            {% endif  %}  
                <div class="d-flex w-100 justify-content-between align-items-center ">
                    <div class="my-1 col-2">
                        <h5>{{ post.title }}</h5>
                    </div>       
                    <div class="my-1 col-1">
                        <spam class="small">Autor</spam>
                        <h6> {{ post.author }}</h6>
                    </div>
                    
                    <div class="my-1 col-1">
                        <spam class="small">Data</spam>
                        <h6><time datetime="YYYY-MM-DD"> {{ post.date_create|date:"d/m/Y" }}</h6>
                    </div>

                    <div class="my-1 col-1">
                        <spam class="small">Tecnologia</spam>
                        <h6> {{ post.category_id.tech }}</h6>
                    </div>

                    <div class="my-1 col-1">
                        <spam class="small">Categoria</spam>
                        <h6> {{ post.category_id.usecase }}</h6>
                    </div>
                                    

                    <div class=" py-1 mx-2 col-2 btn-group" role="group">
                        <button type="button" class="btn btn-info"  data-toggle="tooltip" data-placement="top" title="Editar Post" onclick="window.location='{% url 'view_blog:edit_post' post.id %}';"><i class="material-icons">edit</i></button>
                        {% if post.publi %}
                            <button type="button" class="btn btn-success" data-toggle="tooltip" data-placement="top" title="Desativar Post" onclick="publish_post({{post.id}}, true)" ><i class="material-icons">visibility_off</i></button>
                        {% else %}
                            <button type="button" class="btn btn-warning" data-toggle="tooltip" data-placement="top" title="Publicar Post" onclick="publish_post({{post.id}}, false)" ><i class="material-icons">visibility</i></button>
                        {% endif  %}
                        <button type="button" class="btn btn-danger"  data-toggle="tooltip" data-placement="top" title="Deletar Post" onclick="show_delete_modal({{post.id}})"><i class="material-icons">delete</i></button>
                    </div>
                </div>
            </a>    
        </div>
        {% endfor %}
    </div>
    <div class="tab-pane fade" id="nav-allPubli" role="tabpanel" aria-labelledby="nav-allPubli-tab">
        {% for post in posts %}
        {% if post.publi %}
        <div class="list-group  my-4 ">
                <a  class="list-group-item list-group-item-action flex-column border-success" >
                <div class="d-flex w-100 justify-content-between align-items-center ">
                    <div class="my-1 col-2">
                        <h5>{{ post.title }}</h5>
                    </div>       
                    <div class="my-1 col-1">
                        <spam class="small">Autor</spam>
                        <h6> {{ post.author }}</h6>
                    </div>
                    
                    <div class="my-1 col-1">
                        <spam class="small">Data</spam>
                        <h6><time datetime="YYYY-MM-DD"> {{ post.date_create|date:"d/m/Y" }}</h6>
                    </div>

                    <div class="my-1 col-1">
                        <spam class="small">Tecnologia</spam>
                        <h6> {{ post.category_id.tech }}</h6>
                    </div>

                    <div class="my-1 col-1">
                        <spam class="small">Categoria</spam>
                        <h6> {{ post.category_id.usecase }}</h6>
                    </div>
                                    

                    <div class=" py-1 mx-2 col-2 btn-group" role="group" aria-label="Basic example">
                        <button type="button" class="btn btn-info"  data-toggle="tooltip" data-placement="top" title="Editar Post" onclick="window.location='{% url 'view_blog:edit_post' post.id %}';"><i class="material-icons">edit</i></button>
                        {% if post.publi %}
                            <button type="button" class="btn btn-success" data-toggle="tooltip" data-placement="top" title="Desativar Post" onclick="publish_post({{post.id}}, true)" ><i class="material-icons">visibility_off</i></button>
                        {% else %}
                            <button type="button" class="btn btn-warning" data-toggle="tooltip" data-placement="top" title="Publicar Post" onclick="publish_post({{post.id}}, false)" ><i class="material-icons">visibility</i></button>
                        {% endif  %}
                        <button type="button" class="btn btn-danger"  data-toggle="tooltip" data-placement="top" title="Deletar Post" onclick="show_delete_modal({{post.id}})"><i class="material-icons">delete</i></button>
                    </div>
                </div>
                </a>   
            </div>
            {% endif  %}  
        {% endfor %}
    </div>
    <div class="tab-pane fade" id="nav-allUnpubli" role="tabpanel" aria-labelledby="nav-allUnpubli-tab">
        {% for post in posts %}
        {% if not post.publi %}
            <div class="list-group  my-4 ">
                <a class="list-group-item list-group-item-action flex-column border-warning" >
                <div class="d-flex w-100 justify-content-between align-items-center ">
                    <div class="my-1 col-2">
                        <h5>{{ post.title }}</h5>
                    </div>       
                    <div class="my-1 col-1">
                        <spam class="small">Autor</spam>
                        <h6> {{ post.author }}</h6>
                    </div>
                    
                    <div class="my-1 col-1">
                        <spam class="small">Data</spam>
                        <h6><time datetime="YYYY-MM-DD"> {{ post.date_create|date:"d/m/Y" }}</h6>
                    </div>

                    <div class="my-1 col-1">
                        <spam class="small">Tecnologia</spam>
                        <h6> {{ post.category_id.tech }}</h6>
                    </div>

                    <div class="my-1 col-1">
                        <spam class="small">Categoria</spam>
                        <h6> {{ post.category_id.usecase }}</h6>
                    </div>
                                    

                    <div class=" py-1 mx-2 col-2 btn-group" role="group" aria-label="Basic example">
                        <button type="button" class="btn btn-info"  data-toggle="tooltip" data-placement="top" title="Editar Post" onclick="window.location='{% url 'view_blog:edit_post' post.id %}';"><i class="material-icons">edit</i></button>
                        {% if post.publi %}
                            <button type="button" class="btn btn-success" data-toggle="tooltip" data-placement="top" title="Desativar Post" onclick="publish_post({{post.id}}, true)" ><i class="material-icons">visibility_off</i></button>
                        {% else %}
                            <button type="button" class="btn btn-warning" data-toggle="tooltip" data-placement="top" title="Publicar Post" onclick="publish_post({{post.id}}, false)" ><i class="material-icons">visibility</i></button>
                        {% endif  %}
                        <button type="button" class="btn btn-danger"  data-toggle="tooltip" data-placement="top" title="Deletar Post" onclick="show_delete_modal({{post.id}})"><i class="material-icons">delete</i></button>
                    </div>
                </div>
                </a>   
            </div>
            {% endif  %}  
        {% endfor %}
    </div>
  </div>

</div>


{% endblock %}


{% block script %}

<script>


    function publish_post(id, is_publi){
        console.log(id);
        
        if(is_publi == true){
            bootbox.confirm({
                message: "Deseja retirar a publicação do post?",
                centerVertical: true,
                buttons: {
                    confirm: {
                        label: 'Confirmar',
                        className: 'btn-danger'
                    },
                    cancel: {
                        label: 'Voltar',
                        className: 'btn'
                    }
                },
                callback: function (result) {
                    if (result == true)
                    {
                        window.location = ('/blog/published/'+id+'/False')
                        
                    }
                }
            });
        }
        else
        {
            bootbox.confirm({
                message: "Deseja publicar o post?",
                centerVertical: true,
                buttons: {
                    confirm: {
                        label: 'Publicar',
                        className: 'btn-success'
                    },
                    cancel: {
                        label: 'Voltar',
                        className: 'btn'
                    }
                },
                callback: function (result) {
                    if (result == true)
                    {
                        window.location = ('/blog/published/'+id+'/True')
                    }
                }
            });
        }
    };

    function show_delete_modal(id){
        bootbox.confirm({
            message: "Deseja realizar a exlusão do post?",
            centerVertical: true,
            buttons: {
                confirm: {
                    label: 'Excluir',
                    className: 'btn-danger'
                },
                cancel: {
                    label: 'Voltar',
                    className: 'btn'
                }
            },
            callback: function (result) {
                if (result == true)
                {
                    window.location = ('/blog/delete/'+id)
                }
            }
        });
    };
    
</script>

{% endblock %}

blog/templates/blog/view_post.html
{% extends 'blog/base.html' %}

{% block content %}
<br>

<div class = "container col-lg-10 col-md-8 col-sm-10">
<br>
<br>


    <h5>{{ post.title }}</h5>
    <p><small class="text-muted">{{ post.category_id.tech }} -> {{ post.category_id.usecase }}</small></p>
    <p>{{ post.body_content }}</p>
    <p><small class="text-muted">{{ post.author }} - {{ post.date_create|date:"d/m/Y" }}</small></p>
  
</div>

</div>


{% endblock %}


{% block script %}


{% endblock %}